FROM rabbitmq:3-management

ARG PLUGIN_VERSION=3.13.0
ARG BASE_URL=https://github.com/rabbitmq/rabbitmq-delayed-message-exchange/releases/download
RUN apt-get update && apt-get install -y curl && \
    curl -L "${BASE_URL}/v${PLUGIN_VERSION}/rabbitmq_delayed_message_exchange-${PLUGIN_VERSION}.ez" > \
    $RABBITMQ_HOME/plugins/rabbitmq_delayed_message_exchange-${PLUGIN_VERSION}.ez && \
    rabbitmq-plugins enable --offline rabbitmq_delayed_message_exchange 