apiVersion: v1
kind: Secret
metadata:
  name: catalog-app-secrets 
type: Opaque 
stringData: # stringData avoid coding manually in Base64
  SA_PASSWORD: "Your_password123"
  JWT_KEY: "32plusloooooooongkey_min32symbols"